### ISSUE TITLE
Tracking: initial development

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/IronFenceGate#1]
#### Breaking
An iron fence gate can be broken with any pickaxe. If mined without a pickaxe, it drops nothing.
```
Breaking time
default   25
wooden    3.75
stone     1.9
iron      1.25
diamond   0.95
netherite 0.85
golden    0.65
```

#### Crafting recipe
```
B I B
B I B
```
`B` = iron_bars
`I` = iron_ingot

#### Placing
- [ ] Connects to
  - [ ] cobblestone walls
  - [ ] iron fences
  - [ ] nether brick fences
  - [ ] solid blocks, except glass blocks
  - [ ] wooden fences
- [ ] When placed, a fence gate automatically faces toward the player who placed it, regardless of any other fences around it.
- [ ] A gate may be place whether there is a solid block beneath it or not.
- [ ] A gate floats in mid-air when placed with no connection to anything else.

####  Activation
- [ ] To open or close a fence gate, use the Use Item control.
- [ ] When a fence gate opens or closes, it immediately changes its orientation without affecting anything in the space it "passes through"—moving fence gates don't push entities the way that pistons do.
- [ ] When opened by hand, a fence gate always opens away from the player.

#### Barrier
- [ ] _Although a fence gate appears to be only one block tall, a closed fence gate is a barrier one and a half blocks high. Most mobs cannot jump over a fence gate, and entities on top of the fence gate stand half a block above it._ An iron fence gate will be a two-block tall barrier, do to the necessary `barrier` implementation.
- [ ] An open fence gate is completely non-solid, including the open gates.
- [ ] Multiple open fence gates next to each other can be passed through as if the entire space is open.
- [ ] The sound of opening and closing of a fence gate can be heard up to 16 blocks away, like most [mob](https://minecraft.fandom.com/wiki/Mob) sounds.

#### Redstone component
- [ ] Open/close
  - [ ] redstone
  - [ ] explicit permission node `ironfencegate.use`
